version: '3.8'

services:
  # DynamoDB Local Database
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: iot-dynamodb-local
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    networks:
      - iot-network

  # IoT Smart Home Dashboard Application
  iot-app:
    build: .
    container_name: iot-dashboard
    ports:
      - "5555:5555"
    depends_on:
      - dynamodb
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    networks:
      - iot-network
    restart: unless-stopped

networks:
  iot-network:
    driver: bridge

# Quick commands for Codespace:
# docker-compose up -d              # Start both services
# docker-compose logs -f iot-app    # View app logs  
# docker-compose down              # Stop all services