version: '3.8'

services:
  # DynamoDB Local Database
  dynamodb:
    image: amazon/dynamodb-local:1.21.0
    container_name: iot-dynamodb-local
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    networks:
      - iot-network

  # IoT Smart Home Dashboard Application
  iot-app:
    image: iot-smarthome-dashboard:latest
    container_name: iot-dashboard
    ports:
      - "5555:5555"  # Application port
    depends_on:
      - dynamodb
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    networks:
      - iot-network
    restart: unless-stopped

networks:
  iot-network:
    driver: bridge

# To run this setup:
# 1. Build your Docker image: docker build -t iot-smarthome-dashboard:latest .
# 2. Start services: docker-compose up -d
# 3. View logs: docker-compose logs -f
# 4. Stop services: docker-compose down
# 
# Access:
# - Application: http://localhost:5555
# - DynamoDB Local: http://localhost:8000